// Copies the app's forge-synced ABI JSON into `abis/*.ts` as `as const` arrays so Ponder can
// infer event names and argument types (JSON imports widen `"event"` to `string`, which breaks
// `ponder.on("SeasonMine:RigActivated", ...)` typing). Source of truth stays ../app/src/abi.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../app/src/abi");
const out = resolve(here, "../abis");
const names = ["SeasonMine", "StockFragments", "RedemptionVault"];

mkdirSync(out, { recursive: true });
for (const name of names) {
  const raw = JSON.parse(readFileSync(join(src, `${name}.json`), "utf8"));
  const abi = Array.isArray(raw) ? raw : raw.abi;
  if (!Array.isArray(abi)) throw new Error(`${name}.json: no ABI array found`);
  const body =
    `// Generated by scripts/sync-abis.mjs from ../app/src/abi/${name}.json. Do not edit.\n` +
    `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(out, `${name}.ts`), body);
}
console.log(`sync-abis: wrote ${names.length} files to ${out}`);
